"""process declaration link

Revision ID: dca42e735806
Revises: e4ea861eb93c
Create Date: 2026-09-11 18:08:47.254394
"""
import sqlalchemy as sa
from alembic import op

revision = 'dca42e735806'
down_revision = 'e4ea861eb93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacycare_process_declaration',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('business_process_id', sa.String(length=255), nullable=False),
    sa.Column('privacy_declaration_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_process_id'], ['privacycare_business_process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_process_id', 'privacy_declaration_id', name='uq_privacycare_process_declaration')
    )
    op.create_index(op.f('ix_privacycare_process_declaration_business_process_id'), 'privacycare_process_declaration', ['business_process_id'], unique=False)
    op.create_index(op.f('ix_privacycare_process_declaration_privacy_declaration_id'), 'privacycare_process_declaration', ['privacy_declaration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_privacycare_process_declaration_privacy_declaration_id'), table_name='privacycare_process_declaration')
    op.drop_index(op.f('ix_privacycare_process_declaration_business_process_id'), table_name='privacycare_process_declaration')
    op.drop_table('privacycare_process_declaration')
    # ### end Alembic commands ###
