"""business process

Revision ID: e4ea861eb93c
Revises: 02d3a947b81a
Create Date: 2026-09-11 18:04:18.947885
"""
from alembic import op
import sqlalchemy as sa


revision = 'e4ea861eb93c'
down_revision = '02d3a947b81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacycare_business_process',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_cycle', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('criticality_note', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('last_attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privacycare_business_process')
    # ### end Alembic commands ###
