// This file is auto-generated by @hey-api/openapi-ts

/**
 * AssessmentResponse
 *
 * Response schema for privacy assessments in list views.
 */
export type AssessmentResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Template Id
   */
  template_id: string;
  /**
   * Template Name
   */
  template_name?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Status
   */
  status: string;
  /**
   * Completeness
   */
  completeness?: number;
  /**
   * Risk Level
   */
  risk_level?: string | null;
  /**
   * Risk Band
   */
  // PrivacyCare (fix wave 2026-09-18, risk register review finding 1) — the
  // true four-value band, distinct from the lossy three-value risk_level
  // above (CRITICAL is stored there as "high"). See
  // src/fides/api/privacycare/api/schemas.py's AssessmentResponse.risk_band
  // for the full story.
  risk_band?: string | null;
  /**
   * System Fides Key
   */
  system_fides_key?: string | null;
  /**
   * System Name
   */
  system_name?: string | null;
  /**
   * Declaration Id
   */
  declaration_id?: string | null;
  /**
   * Declaration Name
   */
  declaration_name?: string | null;
  /**
   * Data Use
   */
  data_use?: string | null;
  /**
   * Data Use Name
   */
  data_use_name?: string | null;
  /**
   * Data Categories
   */
  data_categories?: Array<string>;
  /**
   * Created By
   */
  created_by?: string | null;
  /**
   * Created At
   */
  created_at?: string | null;
  /**
   * Updated At
   */
  updated_at?: string | null;
};
